### PR TITLE
Docker volume support

### PR DESCRIPTION
**Pull request by mfp**
Adds support for `--volume` and `--volumes-from`, as well as `--name` (required in practice for the latter).

Also performed slight signature refactoring to make types self-documenting and avoid redundancy.

Untested.

### CODE REVIEW

**Comment by michipili** [comment]
Hi @mfp, thank you for that PR, I have a few questions and remarks about it.

- Polymorphic variants do not work well with merlin autocompletion and I tend to prefer normal variants. In recent OCaml, we can qualify a full expression with a module, so using polymorphic variants is not as useful as it used to be. What are your thoughts about this?

- It is a good thing to factorise the complex signatures through a type, maybe we could go one step beyond in this direction. Why not mimic the structure of the `Rashell_Command` module? We would have a thingi `t` type defined as something similar to

```ocaml
type t = {
  argv:string array;
  entrypoint: string option;
  env: string array;
  image: image_id;
  add_host: (string * string) list;
  cap_add: string list;
  cap_drop: string list;
  device: string list;
  hostname:string;
  link:string list;
  memory: int;
  expose: string list;
  publish:(int*int)list;
  tty:bool;
  remove:bool; (* Attention, I did not see this in your PR! :) *)
  user:string;
  uid:int;
  privileged:bool;
  restart:restart_policy;
  volumes:(volume_source * volume_mountpoint * volume_option list) list;
  volumes_from:container_id list;
}
```

Then a utility function

```ocaml
command: ?add_host:(string * string) list -> ?cap_add:string list -> ?cap_drop:string list -> ?env:string array -> ?device:string list -> ?entrypoint:string -> ?expose:string list -> ?hostname:string -> ?link:string list -> ?memory:int -> ?publish:(int*int)list -> ?tty:bool -> ?user:string -> ?uid:int -> ?privileged:bool -> ?restart:restart_policy -> ?volumes:(volume_source * volume_mountpoint * volume_option list) list -> ?volumes_from:container_id list -> ?argv:string array -> image_id -> t
```

and the `run_*` functions would have types `run_* : t -> 'a Lwt.t` which would closely match the structure of `Rashell_Command`.

If we go this way, we also should

1. Define a `type user = User_ID of int | User_Name of string` to merge fields uid and usernam in the `t` structure.

2. Maybe do something similar for expose and publish fields.

3. Maybe do something similar again for volumes and volumes\_from.

**Comment by mfp** [comment]
I have implemented the type to carry the options. I've left the `image_id` separate since it can be useful to reuse the same set of options to instantiate different images, so the `run_*` functions are of type `options -> image_id -> _`.

I've also merged `uid` and `user` into a single option because they're exclusive. I'd hesitate to do the same for `expose/publish` and `volumes/volumes_from` for a few reasons:
* unlike `uid/user`, they are not exclusive
* doing the merge might leave users accustomed to docker's command line arguments scratching their heads
* keeping different labels is more convenient for the user, especially for the common case where you only use one of them (e.g. `~volumes_from:["foo"; "bar"; "baz"]` vs. `~volumes:[Volumes_From "foo"; Volumes_From "bar"; Volumes_From "baz"]`.

BTW, I noticed that `expose` is a string list, and not an int list. Does docker allow symbolic names (like "http" or such)? [Docker's reference docs](http://docs.docker.com/engine/reference/builder/#expose) don't indicate so (nor the opposite).

**Comment by mfp** [comment]
One last thing. I've made the `options` type abstract (as a conservative API decision, since you can always expose it at a latter time, and the other way around is painful), but if it is deemed that allowing to tweak options as in `{ options with ... = ... }` is useful and desirable, it can be exposed right away.

**Comment by michipili** [comment]
Hi thank you for your fixes, good work, and your detailed feedback, it is much appreciated!

I agree your points for expose/publish and volumes/volumes_from. For the type of expose, I think it is fine to stay by string instead of integer – the port is not “really” an integer, I mean we cannot add or withdraw anything from it, it is just a form of an id and a placeholder for some bits of information.

I am not sure why you want to single out the `image` arguments out of the `options` type, as this singling out is likely to be relevant for some specific use-cases. Would it be fine for you to:

1. Rename the options type to `t` and the `options` function to something like `command` or `spec` ?
2. Turn the `t` type into a concrete type?

The fields of the struct are essentially independent one of each other and the struct only serves as grab-pack of parameters, so I guess it is fine to expose it, and it makes it easy to edit a struct, it can be printed in the toplevel, etc.

Asides from that I spotted some `(***` instead of `(**` in your comments, which is probably not your intent.

**Comment by mfp** [comment]
On Mon, Dec 07, 2015 at 12:04:52AM -0800, Michael Grünewald wrote:
> I agree your points for expose/publish and volumes/volumes_from. For the type of expose, I think it is fine to stay by string instead of integer – the port is not “really” an integer, I mean we cannot add or withdraw anything from it, it is just a form of an id and a placeholder for some bits of information.

One argument for using an integer instead of a string is that it enforces
Docker's expectations (as I said, nowhere in its docs did I find anything
hinting that symbolic names were accepted). Instead of having a runtime error
returned by docker, the developer would get a type error.

> I am not sure why you want to single out the `image` arguments out of the
> `options` type, as this singling out is likely to be relevant for some
> specific use-cases. Would it be fine for you to:
> 
> 1. Rename the options type to `t` and the `options` function to something like `command` or `spec` ?
> 2. Turn the `t` type into a concrete type?
> 
> The fields of the struct are essentially independent one of each other and the struct only serves as grab-pack of parameters, so I guess it is fine to expose it, and it makes it easy to edit a struct, it can be printed in the toplevel, etc.

I have exposed the options type.

The idea behind separating the image_id and the options is that you might want
to use the same options to run different images. With the current signature,
you can easily build the options once and reuse them, e.g.

    let opts = Rashell_Docker.options ~memory ~user ~volumes_from ~volumes () in
    ...
    lwt c1 = Rashell_Docker.run opts "img1"
    and c2 = Rasheel_Docker.run { opts with publish = [...] } "img2" in

The options function provides suitable defaults and is much more convenient
than manual creation of the record.

The situation differs from Rashell_Command's in two ways:
    (1) there are many more options
    (2) most options are not tied to a particular image (i.e., can be reused
        to launch multiple containers for different images)

This is why I feel it's cleaner to separate the image_id from the options
instead of adding an "image_id" field to the "options" type and renaming the
latter to "command". Now that the type is concrete, though, it doesn't really
matter that much (separating the options from the image_id was a must when the
type was abstract, though).

> Asides from that I spotted some `(***` instead of `(**` in your comments, which is probably not your intent.

These are not my comments ;-) but 2dd42efd's. I fixed them anyway.

-- 
Mauricio Fernández

**Comment by michipili** [comment]
Hi Mauricio, thank you for your feedback!

> One argument for using an integer instead of a string is that it enforces […]

All right, let's use an integer then.

> The idea behind separating the image_id and the options is that you might want to use the same options to run different images.

I understand this, however it does not make a reason for `image_id` to be treated specially: sometimes you want to run the very same command with different images (e.g. bisecting functional testings) but there are other plausible arguments for each single field in the options type – like you want to run several times the same service but bind it to different ports on the host machine, or bisect on the amount of memory the container is allowed to use, and in this case, having the image as a separated argument feels a bit clumsy.

A more important point, is the ability to run jobs in parallel, where we want to use a pattern where

1. We produce a list of job descriptions (Rashell_Command.t, Rashell_Docker.t, or Rashell_OpenSsh.t when I am done writing it)
2. We use a runner command to (Rashell_Command.exec_query, Rashell_Docker.run_query. Rashell_OpenSsh.run_query) turn these job descriptions into Lwt.t running concurrently.
3.We join all the threads.

Mut maybe you have a concrete a use-case where it is much better to have the image separated?

Anyway, with an image list, and a concrete type it is very easy to write sth like

```ocaml
let options = { …; image_id = "this-is-not-a-valid-image-id"; }
let image_ids = [ "id1"; "id2" ]
let jobs = List.map (fun image_id -> { options with image_id }) image_ids
```

> These are not my comments ;-) but 2dd42ef's. I fixed them anyway.

Thanks! :D

**Comment by mfp** [comment]
On Wed, Dec 09, 2015 at 06:39:50AM -0800, Michael Grünewald wrote:
> I understand this, however it does not make a reason for `image_id` to be treated specially: sometimes you want to run the very same command with different images (e.g. bisecting functional testings) but there are other plausible arguments for each single field in the options type – like you want to run several times the same service but bind it to different ports on the host machine, or bisect on the amount of memory the container is allowed to use, and in this case, having the image as a separated argument feels a bit clumsy.
> 
> A more important point, is the ability to run jobs in parallel, where we want to use a pattern where
> 
> 1. We produce a list of job descriptions (Rashell_Command.t, Rashell_Docker.t, or Rashell_OpenSsh.t when I am done writing it)
> 2. We use a runner command to (Rashell_Command.exec_query, Rashell_Docker.run_query. Rashell_OpenSsh.run_query) turn these job descriptions into Lwt.t running concurrently.
> 3.We join all the threads.
> 
> Mut maybe you have a concrete a use-case where it is much better to have the image separated?

Once the type is concrete, it all boils down to a stylistic issue (e.g., with
the separate image_id, concurrent execution would become
`Lwt_list.map_p (fun (options, image_id) -> Rashell_Docker.run options image_id) l`).

So, for symmetry with Rashell_Command, I've included the image_id in the type,
and renamed it to `command` (not `t`, because it's not entirely clear what a
`Rashell_Docker.t` should represent: a runnable container, a running one, an
image?).

-- 
Mauricio Fernández

**Comment by michipili** [comment]
That is great, thank you for your help!  I am very happy to merge this. :)
I hope to be able to roll out v0.3.0 pretty soon! :)

As a side note, `bmake` has a very nice feature that allows to put objects in a repository distinct from the source directory. In a few words, I only need to say (pay attention, the simple quotes are intended!)

```
MAKEOBJDIR='/home/michael/obj${.CURDIR:S@/home/michael@@:S@/usr@@}${ARCHITECTUREDIR}${CONFIGURATIONDIR}'
export MAKEOBJDIR
```

and when I work in `/home/michael/Workshop/project` all objects end up in `/home/michael/obj/Workshop/project` If I use configurations (usually in Makefile.local to switch between production and debug mode) or architectures (for C projects), these elements are also used to extend the name.

**See Also** https://github.com/michipili/bsdowl/blob/master/doc/DevelopOCamlSoftware.md#manage-compilation-configurations

**Pull request merged**
