### PR TITLE
Support labels in Docker images/containers.

### PR DESCRIPTION
**Pull request by mfp**

### CODE REVIEW

**Comment by michipili** [comment]
Hi! Thank you for doing this! ☺  Before I review with due attention, I have a quick question: In the ATD file, why did you prefer `~label` over `?label` ?

**Comment by mfp** [comment]
On Mon, Dec 14, 2015 at 10:23:11AM -0800, Michael Grünewald wrote:
> Hi! Thank you for doing this! ☺  Before I review with due attention, I have a quick question: In the ATD file, why did you prefer `~label` over `?label` ?

`?labels` results in the field having value None when missing,
`~labels` allows to have the empty list [] as the default value.

-- 
Mauricio Fernández

**Comment by michipili** [comment]
It looks good, thanks! :)

**Comment by michipili** [comment]
P.S. It looks like you are preparing another PR adding `~chomp` to some command, should we handle this right away?

**Comment by mfp** [comment]
On Sun, Dec 20, 2015 at 02:36:02AM -0800, Michael Grünewald wrote:
> P.S. It looks like you are preparing another PR adding `~chomp` to some command, should we handle this right away?

It's a trivial one-liner, but I'm creating the PR anyway so that you can
"one-click merge" it :)

-- 
Mauricio Fernández

**Pull request merged**
